name: Build Docker

on:
  push:
    branches:
      - 'main'
      - '**'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      - 
        name: Checkout branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Build Dockerfile
        run: docker build . --file Dockerfile --tag alpine:$(date +%s)
